app/rent4u/views.py
import os
from flask import Blueprint, flash, redirect,render_template, request, send_from_directory, url_for
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename

from app import ALLOWED_EXTENSIONS, db, app
from app.rent4u.models import Car, CarForm, Contact, ContactForm, Reservation, ReservationForm, SearchForm, Customer
from app.auth.views import admin_required

rent4u = Blueprint('rent4u', __name__)

@rent4u.route('/')
@rent4u.route('/index')
@rent4u.route('/home')
def index():
    form= SearchForm()
    # if current_user.is_authenticated:
        # print(current_user.username)
        # print(current_user.is_admin())
    return render_template('index.html', is_home_page=True, form=form)

@rent4u.route('/about')
def about():
    return render_template('about.html')

@rent4u.route('/blog')
def blog():
    return render_template('blog.html')

@rent4u.route('/car')
def car():
    return render_template('car.html')

@rent4u.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm()

    if form.validate_on_submit():
        new_contact = Contact(
            name=form.name.data,
            phone=form.phone.data,
            email=form.email.data,
            message=form.message.data
        )

        db.session.add(new_contact)
        db.session.commit()

        flash('Your message has been submitted!', 'success')
        return redirect(url_for('rent4u.contact'))

    return render_template('contact.html', form=form)

@rent4u.route('/search', methods=['GET'])
def search():
    form = SearchForm(request.args)
    # if form.validate_on_submit():
    #     print("AAAAA")
    # cars=Car.query.all()
    #products = Product.query.paginate(page=page, per_page=5).items
    
    print(form.pick_up_date)
    
    query = Car.query

    query = query.filter(Car.availability == True)
    
    car_type = request.args.get('type')
    if car_type:
        if not car_type=="any":
            query = query.filter(Car.type == car_type)

    transmission = request.args.get('transmission')
    if transmission:
        if transmission != "both":
            query = query.filter(Car.transmission == transmission)

    seats = request.args.get('seats')
    if seats:
        query = query.filter(Car.seats >= seats)

    luggage = request.args.get('luggage')
    if luggage:
        query = query.filter(Car.luggage >= luggage)

    min_price = request.args.get('min_price')
    max_price = request.args.get('max_price')
    if min_price and max_price:
        query = query.filter(Car.rental_rate.between(min_price, max_price))

    if form.sort_by.data == 'price_ascending':
        query = query.order_by(Car.rental_rate.asc())
    elif form.sort_by.data == 'price_descending':
        query = query.order_by(Car.rental_rate.desc())
    
    
    
    page = request.args.get('page', 1, type=int)
    cars = query.paginate(page=page, per_page=10)
    # print(page)
    return render_template('search.html',form=form, cars=cars)
    # return redirect(url_for('rent4u.index'))

@admin_required
@rent4u.route('/add_car', methods=['GET', 'POST'])
def add_car():
    form = CarForm()
    
    if form.validate_on_submit():
        # print(form.image.data)
        # print(request.files.keys())
        if form.image.data:
            image_file = form.image.data
            filename = secure_filename(image_file.filename)
            image_path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
            image_file.save(image_path)
        
        new_car = Car(
            type=form.type.data,
            transmission=form.transmission.data,
            seats=form.seats.data,
            brand=form.brand.data,
            model=form.model.data,
            doors=form.doors.data,
            luggage=form.luggage.data,
            # year=form.year.data,
            # color=form.color.data,
            # license_plate=form.license_plate.data,
            availability= form.availability.data == 'available',
            # current_location=form.current_location.data,
            rental_rate=form.rental_rate.data,
            # description=form.description.data,
            image_filename=filename if form.image.data else None
        )

        db.session.add(new_car)
        db.session.commit()

        flash('Car added successfully!', 'success')
        return redirect(url_for('rent4u.add_car'))  # Update this route

    return render_template('add_car.html', form=form)

@rent4u.route('/car_image/<filename>')
def car_image(filename):
    return send_from_directory(app.config['UPLOAD_FOLDER'], filename)
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

from app import csrf

@rent4u.route('/uploadtest', methods=['GET', 'POST'])
@csrf.exempt
def upload_file():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        print(request.files.keys())
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            return redirect(url_for('rent4u.upload_file'))
    return '''
            <!doctype html>
            <title>Upload new File</title>
            <h1>Upload new File</h1>
            <form method=post enctype=multipart/form-data>

            <input type=file name=file>
            <input type=submit value=Upload>
            </form>
            '''

@login_required
@rent4u.route('/reservation', methods=['GET', 'POST'])
def reservation():
    # customer_id = current_user.customer.id if current_user.is_authenticated else None
    # car_id = request.args.get('car_id')
    # pick_up_date = request.args.get('pick_up_date')
    # return_date = request.args.get('return_date')
    # pick_up_location = request.args.get('pick_up_location')
    # return_location = request.args.get('return_location')
    
    # # car = Car.query.get({"id":car_id})
    # car = Car.query.get_or_404(car_id)
    
    form = ReservationForm()
    
    if form.validate_on_submit():
        car_id = form.car_id.data
        # pick_up_date = form.pick_up_date.data
        # return_date = form.return_date.data
        # pick_up_location = form.pick_up_location.data
        # return_location = form.return_location.data
        reservation = Reservation(
                        customer_id = current_user.customer.id,
                        car_id = form.car_id.data,
                        pick_up_date = form.pick_up_date.data,
                        return_date = form.return_date.data,
                        pick_up_location = form.pick_up_location.data,
                        return_location = form.return_location.data
                        )
        db.session.add(reservation)
        car = Car.query.get_or_404(car_id)
        car.availability = False
        db.session.commit()
        flash('Reservation successful', "success")
        return render_template('reservation.html', car = car, form = form, done=True)
    else:  
        car_id = request.args.get('car_id')
        car = Car.query.get_or_404(car_id)
        form = ReservationForm(request.args)
        return render_template('reservation.html', car = car, form = form)
# pickUpDate=pickUpDate, returnDate=returnDate, pickUpLocation=pickUpLocation, returnLocation=returnLocation

@login_required
@rent4u.route('/reservations', methods=['GET'])
def reservations():
    reservations = Reservation.query.filter_by(customer_id=current_user.customer.id).all()
    # print(current_user.customer.id)
    return render_template('reservations.html', reservations=reservations)

app/templates/about.html
{% extends "base.html" %}
{% block content %}
  <!-- about section -->

  <section class="about_section layout_padding2-top layout_padding-bottom ">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-7 px-0">
          <div class="img-box">
            <img src="{{ url_for('static', filename='images/about-img.png') }}" alt="">
          </div>
        </div>
        <div class="col-md-4 col-lg-3">
          <div class="detail-box">
            <h2>
              About Our Cars
            </h2>
            <p>
              It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->
{% endblock content %}

app/templates/add_car.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center my-5">
        <div class="col-md-8">
            <h2 class="mb-4">Add a New Car</h2>
            <form method="POST" action="{{ url_for('rent4u.add_car') }}" enctype="multipart/form-data" role="form">
                {{ form.hidden_tag() }}
                <div class="mb-3">{{ form.type.label(class="form-label") }}:{{ form.type(class="form-control") }}</div>
                <div class="mb-3">{{ form.transmission.label(class="form-label") }}:{{ form.transmission(class="form-select") }}</div>
                <div class="mb-3">{{ form.seats.label(class="form-label") }}:{{ form.seats(class="form-control") }}</div>
                <div class="mb-3">{{ form.doors.label(class="form-label") }}:{{ form.doors(class="form-control") }}</div>
                <div class="mb-3">{{ form.luggage.label(class="form-label") }}:{{ form.luggage(class="form-control") }}</div>
                <div class="mb-3">{{ form.brand.label(class="form-label") }}:{{ form.brand(class="form-control") }}</div>
                <div class="mb-3">{{ form.model.label(class="form-label") }}:{{ form.model(class="form-control") }}</div>
                
                
                {#<div class="mb-3">{{ form.year.label(class="form-label") }}:{{ form.year(class="form-control") }}</div>
                <div class="mb-3">{{ form.color.label(class="form-label") }}:{{ form.color(class="form-control") }}</div>
                <div class="mb-3">{{ form.license_plate.label(class="form-label") }}:{{ form.license_plate(class="form-control") }}</div>#}

                <div class="mb-3">{{ form.availability.label(class="form-label") }}:{{ form.availability(class="form-select") }}</div>
                {#<div class="mb-3">{{ form.current_location.label(class="form-label") }}:{{ form.current_location(class="form-control") }}</div>#}
                <div class="mb-3">{{ form.rental_rate.label(class="form-label") }}:{{ form.rental_rate(class="form-control") }}</div>
                {#<div class="mb-3">{{ form.description.label(class="form-label") }}:{{ form.description(class="form-control") }}</div>#}
                <div class="mb-3">{{ form.image.label(class="form-label") }}:{{ form.image(class="form-control") }}</div>

                <button type="submit" class="btn background_color">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}  

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Rent4u</title>

  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.css') }}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,600,700&display=swap" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{{ url_for('static', filename='css/responsive.css') }}" rel="stylesheet" />
</head>

<body {% if not is_home_page %}class="sub_page"{% endif %}>
    {% include "header.html" %}
    {% if not is_home_page %}
      <div> 
          {% for category, message in get_flashed_messages(with_categories=true) %} 
              <br/> 
              <div class="alert alert-{{category}} alert-dismissable fade show" role="alert"> 
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button> 
                  {{ message }} 
              </div> 
          {% endfor %} 
      </div>
    {% endif %}
    
    <div class="content">
    {% block content %}{% endblock %}
    </div>
    {% include "footer.html" %}

  <script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <script src="{{ url_for('static', filename='js/custom.js') }}"></script>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>

</html>

app/templates/blog.html
{% extends "base.html" %}
{% block content %}

  <!-- blog section -->

  <section class="blog_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          Our Latest Blog
        </h2>
        <p>
          It is a long established fact that a reader will be distracted by the
        </p>
      </div>
    </div>
    <div class="blog_container">
      <div class="layout_padding2-top">
        <div class="carousel-wrap ">
          <div class="owl-carousel">
            <div class="item">
              <div class="box">
                <div class="date-box">
                  <h6>
                    04 Nov 2019
                  </h6>
                </div>
                <div class="img-box">
                  <img src="{{ url_for('static', filename='images/b-1.jpg') }}" alt="">
                </div>
                <div class="detail-box">
                  <h5>
                    Vintage
                  </h5>
                  <p>
                    It is a long established fact that a reader will be distracted by the readable The point of using Lorem </p>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="box">
                <div class="date-box">
                  <h6>
                    04 Nov 2019
                  </h6>
                </div>
                <div class="img-box">
                  <img src="{{ url_for('static', filename='images/b-2.jpg') }}" alt="">
                </div>
                <div class="detail-box">
                  <h5>
                    Steering wheels
                  </h5>
                  <p>
                    It is a long established fact that a reader will be distracted by the readable The point of using Lorem </p>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="box">
                <div class="date-box">
                  <h6>
                    04 Nov 2019
                  </h6>
                </div>
                <div class="img-box">
                  <img src="{{ url_for('static', filename='images/b-3.jpg') }}" alt="">
                </div>
                <div class="detail-box">
                  <h5>
                    Buick Car
                  </h5>
                  <p>
                    It is a long established fact that a reader will be distracted by the readable The point of using Lorem </p>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="box">
                <div class="date-box">
                  <h6>
                    04 Nov 2019
                  </h6>
                </div>
                <div class="img-box">
                  <img src="{{ url_for('static', filename='images/b-2.jpg') }}" alt="">
                </div>
                <div class="detail-box">
                  <h5>
                    Steering wheels
                  </h5>
                  <p>
                    It is a long established fact that a reader will be distracted by the readable The point of using Lorem </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end blog section -->
{% endblock content %}

app/templates/car.html
{% extends "base.html" %}
{% block content %}
  {% include "content/car_content.html" %}
{% endblock content %}  

app/templates/contact.html
{% extends "base.html" %}
{% block content %}
  {% include "content/contact_content.html" %}
{% endblock content%}

app/templates/footer.html
<footer class="container-fluid footer_section">
    <p>
      Copyright &copy; 2020 All Rights Reserved. Design by
      <a href="https://html.design/">Free Html Templates</a>
    </p>
</footer>

app/templates/reservation.html
{% extends "base.html" %}

{% block content %}
    <div class="container col-md-8 mt-5">
        <form method="POST" action="{{ url_for('rent4u.reservation') }}" role="form" >
            <div class="row align-items-end mb-3">
                {{ form.csrf_token }}
                <input type="hidden" name="car_id" value="{{ car.id }}">
                {# <div class="col-md-2">
                    <label for="parkingName">Pick Up Locaion</label>
                    <input type="text" class="form-control" id="pick_up_location" name="pick_up_location" value="Paris">
                </div>
                <div class="col-md-2">
                    <label for="parkingNumber">Drop Location</label>
                    <input type="text" class="form-control" id="return_location" name="return_location" value="Orleans">
                  </div>
                <div class="col-md-2">
                    <label for="parkingName">Pick Up Date</label>
                    <input type="date" class="form-control" id="pick_up_date" name="pick_up_date" value="2023-12-20">
                  </div>
                <div class="col-md-2">
                    <label for="parkingNumber">Return Date</label>
                    <input type="date" class="form-control" id="return_date" name="return_date" value="2023-12-27">
                </div> #}
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.pick_up_location.label(class="form-label") }}{{ form.pick_up_location(class="form-control", readonly="readonly") }}</div>
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.return_location.label(class="form-label") }}{{ form.return_location(class="form-control", readonly="readonly") }}</div>
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.pick_up_date.label(class="form-label") }}{{ form.pick_up_date(class="form-control", readonly="readonly") }}</div>
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.return_date.label(class="form-label") }}{{ form.return_date(class="form-control", readonly="readonly") }}</div>
                {% if not done %}
                    <div class="col-md-2"><button type="submit" class="btn background_color w-100">Confirm</button></div>
                {% endif %}
                
            </div>
        </form>
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="card-body col-md-4 text-center">
                            {% if car.image_filename %}
                                <img src="{{ url_for('rent4u.car_image', filename=car.image_filename) }}" class="img-fluid rounded" alt="Car Image" style="object-fit: contain; height: 100%">
                            {% else %}
                                <img src="" class="img-fluid rounded" alt="Placeholder Image">
                            {% endif %}
                        </div>
                        <div class="col-md-8 row g-0">
                            <h5 class="card-title m-2">{{ car.brand }} {{ car.model }}</h5>
                            <div class="card-body col-md-6">
                                <p class="card-text"><strong>Type:</strong> {{ car.type }}</p>
                                <p class="card-text"><strong>Transmission:</strong> {{ car.transmission }}</p>
                                <p class="card-text"><strong>Seats:</strong> {{ car.seats }}</p>
                                
                            </div>
                            <div class="card-body col-md-6 d-flex flex-column">
                                <div class="align-self-start">
                                    <p class="card-text"><strong>Doors:</strong> {{ car.doors }}</p>
                                    <p class="card-text"><strong>Luggage Capacity:</strong> {{ car.luggage }}</p>
                                    <!-- <p class="card-text"><strong>Availability:</strong> {{ "Available" if car.availability else "Unavailable" }}</p> -->
                                    <!-- <p class="card-text"><strong>Current Location:</strong> {{ car.current_location }}</p> -->
                                    <p class="card-text"><strong>Rental Rate per Day:</strong> ${{ car.rental_rate }}</p>
                                    <!-- <p class="card-text"><strong>Description:</strong> {{ car.description }}</p> -->
                                </div>
                            
                                <div class="flex-grow-1"></div>
                            
                                {# <div class="align-self-end w-50 card-text">
                                    <a href="{{ url_for('rent4u.reservation', car_id=car.id, pickUpDate=request.args.get('pickUpDate'), returnDate=request.args.get('returnDate'), pickUpLocation=request.args.get('pickUpLocation'), returnLocation=request.args.get('returnLocation')) }}" class="btn background_color w-100 mt-2">Select</a>
                                </div> #}
                            </div>
                        </div>
                    </div>
                </div>
                {% if done %}
                    <div>
                        <a href="{{ url_for('rent4u.index') }}" class="btn background_color btn-large">Return to Home Page</a>
                    </div>
                {% endif %}
                
    </div>
{% endblock content %}

app/templates/search.html
{% extends "base.html" %}

{% block content %}
    <div class="container col-md-8 mt-5">
        <form method="GET" action="{{ url_for('rent4u.search') }}" role="form" >
            <div class="row align-items-end mb-3">
                <!-- <div class="col-md-2">
                    <label for="parkingName">Pick Up Locaion</label>
                    <input type="text" class="form-control" id="pick_up_location" name="pick_up_location" value="{{ form.pick_up_location.value }}">
                </div>
                <div class="col-md-2">
                    <label for="parkingNumber">Drop Location</label>
                    <input type="text" class="form-control" id="return_location" name="return_location" value="{{ form.return_location.value }}">
                  </div>
                <div class="col-md-2">
                    <label for="parkingName">Pick Up Date</label>
                    <input type="date" class="form-control" id="pick_up_date" name="pick_up_date" value="{{ form.pick_up_date.value }}">
                  </div>
                <div class="col-md-2">
                    <label for="parkingNumber">Return Date</label>
                    <input type="date" class="form-control" id="return_date" name="return_date" value="{{ form.return_date.value }}">
                </div> -->
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.pick_up_location.label(class="form-label") }}{{ form.pick_up_location(class="form-control") }}</div>
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.return_location.label(class="form-label") }}{{ form.return_location(class="form-control") }}</div>
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.pick_up_date.label(class="form-label") }}{{ form.pick_up_date(class="form-control") }}</div>
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.return_date.label(class="form-label") }}{{ form.return_date(class="form-control") }}</div>
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.sort_by.label(class="form-label") }}{{ form.sort_by(class="form-select") }}</div>
                <div class="col-md-2"><button type="submit" class="btn background_color w-100">Submit</button></div>
            </div>
            <div class="row mb-3">
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.type.label(class="form-label") }}{{ form.type(class="form-select") }}</div>
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.transmission.label(class="form-label") }}{{ form.transmission(class="form-select") }}</div>
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.seats.label(class="form-label") }}{{ form.seats(class="form-control") }}</div>
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.luggage.label(class="form-label") }}{{ form.luggage(class="form-control") }}</div>
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.rental_rate_min.label(class="form-label") }}{{ form.rental_rate_min(class="form-control") }}</div>
                <div class="col-sm-2 d-flex flex-column justify-content-end">{{ form.rental_rate_max.label(class="form-label") }}{{ form.rental_rate_max(class="form-control") }}</div>
            </div>
            
        </form>
        <div>total of {{cars.total}} results</div>
        {% for car in cars.items %}
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="card-body col-md-4 text-center">
                            {% if car.image_filename %}
                                <img src="{{ url_for('rent4u.car_image', filename=car.image_filename) }}" class="img-fluid rounded" alt="Car Image" style="object-fit: contain; height: 100%">
                            {% else %}
                                <img src="" class="img-fluid rounded" alt="Placeholder Image">
                            {% endif %}
                        </div>
                        <div class="col-md-8 row g-0">
                            <h5 class="card-title m-2">{{ car.brand }} {{ car.model }}</h5>
                            <div class="card-body col-md-6">
                                <p class="card-text"><strong>Type:</strong> {{ car.type }}</p>
                                <p class="card-text"><strong>Transmission:</strong> {{ car.transmission }}</p>
                                <p class="card-text"><strong>Seats:</strong> {{ car.seats }}</p>
                                
                            </div>
                            <div class="card-body col-md-6 d-flex flex-column">
                                <div class="align-self-start">
                                    <p class="card-text"><strong>Doors:</strong> {{ car.doors }}</p>
                                    <p class="card-text"><strong>Luggage Capacity:</strong> {{ car.luggage }}</p>
                                    <!-- <p class="card-text"><strong>Availability:</strong> {{ "Available" if car.availability else "Unavailable" }}</p> -->
                                    <!-- <p class="card-text"><strong>Current Location:</strong> {{ car.current_location }}</p> -->
                                    <p class="card-text"><strong>Rental Rate per Day:</strong> ${{ car.rental_rate }}</p>
                                    <!-- <p class="card-text"><strong>Description:</strong> {{ car.description }}</p> -->
                                </div>
                            
                                <div class="flex-grow-1"></div>
                            
                                <div class="align-self-end w-50 card-text">
                                    <a href="{{ url_for('rent4u.reservation', car_id=car.id, pick_up_date=request.args.get('pick_up_date'), return_date=request.args.get('return_date'), pick_up_location=request.args.get('pick_up_location'), return_location=request.args.get('return_location')) }}" class="btn background_color w-100 mt-2">Select</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- <script>
                    var currentDate = new Date();
                  
                    var pickUpDateInput = document.getElementById('pickUpDate');
                    pickUpDateInput.value = currentDate.toISOString().split('T')[0];
              
                    var returnDate = new Date(currentDate);
                    returnDate.setDate(currentDate.getDate() + 7);
                    var returnDateInput = document.getElementById('returnDate');
                    returnDateInput.value = returnDate.toISOString().split('T')[0];
                  
                </script> -->
        {% endfor %}

        {#{% if cars.has_prev %} 
        <a href="{{ url_for(request.endpoint, page=cars.prev_num) }}"> 
            {{"<< Previous Page"}} 
        </a>
        {% else %} 
            {{"<< Previous Page"}} 
        {% endif %} | 
        {% if cars.has_next %} 
            <a href="{{ url_for(request.endpoint, page=cars.next_num) }}"> 
                {{"Next page >>"}} 
            </a> 
        {% else %}
            {{"Next page >>"}} 
        {% endif %}#}
        <div class="text-center mb-3">
            {% if cars.has_prev %}

            {% set args = request.args.to_dict() %}
            {% set _ = args.update({'page': cars.prev_num}) %}
            <a href="{{ url_for(request.endpoint, **args) }}" class="btn background_color">&lt;</a>

            {% endif %}

            Page {{ cars.page }} of {{ cars.pages }}

            {% if cars.has_next %}

                {% set args = request.args.to_dict() %}
                {% set _ = args.update({'page': cars.next_num}) %}
                <a href="{{ url_for(request.endpoint, **args) }}" class="btn background_color">&gt;</a>

            {% endif %}
        </div>   
    </div>
{% endblock content %}